ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
]

ecommerce/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('a/',views.home),
    path('contactus/',views.contactus),
    path('aboutus/',views.aboutus),
    path('getEmployees/',views.getEmployees),
    path('addstudent/',views.StudentView.as_view(),name='addstudent'),
    path('studentlist/',views.StudentListView.as_view(),name='studentlist'),
    path('deletestudent/<int:pk>',views.StudentDeleteView.as_view(),name='deletestudent'),
    path('studentdetail/<int:pk>',views.StudentDetailView.as_view(),name='studentdetail'),
    path('studentupdate/<int:pk>',views.StudentUpdateView.as_view(),name='studentupdate'),
    
    
]

ecommerce/home/models.py
from statistics import mode

from django.db import models

# Create your models here.
#class baesd models..
class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    age = models.IntegerField()
    isActive = models.BooleanField(default=True)
    address = models.TextField()
    joining_date = models.DateField(null=True, blank=True)
    
    class Meta:
        db_table = 'student'
        
    def __str__(self):
        return self.name    

CHOICE = [
    ("work from home","work from home"),
    ("work from office","work from office")
]
class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    salary = models.FloatField()
    contactNo = models.CharField(max_length=100)
    workchoice = models.CharField(max_length=100,choices=CHOICE)
    isMarried = models.BooleanField(null=True)
    
    class Meta:
        db_table = "employee"
        
    def __str__(self):
        return self.name   

catChoice = [
    ("Eletronices","eletoronics"),
    ("Fashion","fashion"),
    ("Books","books"),
]
class Category(models.Model):            
    name = models.CharField(max_length=100,choices=catChoice)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.FloatField() 
    qty = models.IntegerField()    
    
    def __str__(self):
        return self.name
    

cchoice = [
    ("java",("fs,es,google")),
    ("php",("yt,clg")),
    ("python",("uni,ech")),
]

class Tut(models.Model):
    name=models.CharField(max_length=100)
    choice = models.CharField(max_length=100,choices=cchoice)    

ecommerce/home/views.py
from django.http import HttpResponse

from django.shortcuts import render

from .models import Employee, Student
from django.template import context
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView,DetailView

# Create your views here.
#function based view

def home(request):
    return HttpResponse("Hello World")

def contactus(request):
    return render(request,'contactus.html')

def aboutus(request):
    return render(request,' l')


# order by name
# married wf saalry 5000

def getEmployees(request):
    #queryset
    employees = Employee.objects.all().values_list()
    employees1 = Employee.objects.filter(name='amit').values_list()
    employees2  =Employee.objects.filter(name__endswith='t').values_list()
    employees3 = Employee.objects.filter(salary__gte=(1500)).values_list()
    employees4 = Employee.objects.filter(workchoice="work from home").values_list()
    employees5 = Employee.objects.filter(isMarried=True).values_list()
    #salary gt 1500 and work from homr
    employees6 = Employee.objects.filter(salary__gt=(1500),workchoice="work from home").values_list()
    employees7 = Employee.objects.filter(salary__gt=(1500)).order_by('salary').values_list()
    context = {
        'employees':employees7
    }
    return render(request,"home/employees.html",context)
    
class StudentView(CreateView):
    model=Student
    fields= '__all__'
    template_name = 'home/student.html'
    success_url="/home/studentlist"
    
class StudentListView(ListView):
    model = Student
    template_name = 'home/studentlist.html'
    context_object_name = 'students'
    
        
class StudentDeleteView(DeleteView):
    model = Student
    template_name = 'home/studentdelete.html'
    success_url = '/home/studentlist'         
    
class StudentDetailView(DetailView):
    model = Student
    template_name = 'home/studentdetail.html'
    context_object_name = 'student'

class StudentUpdateView(UpdateView):
    model = Student
    fields = '__all__'
    template_name = 'home/studentupdate.html'
    success_url = '/home/studentlist'    

ecommerce/templates/contactus.html
<h1>

    CONTACT US
</h1>

ecommerce/templates/home/aboutus.html
<h1>About us</h1>

ecommerce/templates/home/employees.html
<h1>EMPLOYEES</h1>
{{employees}}

ecommerce/templates/home/student.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% load crispy_forms_tags %}

<form>
    {{ form|crispy }}
    {% csrf_token %}
    <input class = "btn btn-primary"type="submit" value="Submit" />
</form>
    
{% comment %} 
    <form method = "post">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1"></label>
          {{form.name | as_crispy_field}}
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1"></label>
            {{form.joining_date | as_crispy_field}}
          </div>
        
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form> {% endcomment %}

ecommerce/templates/home/studentdelete.html
<form method = "post">
    {% csrf_token %}
    <input type = "submit" value = "confirm">
</form>

ecommerce/templates/home/studentdetail.html
card
{{student.name}}

ecommerce/templates/home/studentlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel ="stylesheet"  href = "{% static 'style.css'%}">
</head>
<body>

    
<h1>STUDENT LIST</h1>
<img src="{% static 'images/1.jpg'%}" alt="">


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Age</th>
      <th scope="col">Is Active</th>
      <th scope="col">ACtion</th>

    </tr>
  </thead>
  <tbody>
    {% for x in students  %}
    <tr>
      <th scope="row">
       <a href = "{% url 'home:studentdetail' x.pk %}" >{{x.id}}</a>
      </th>
      <td>{{x.name}}</td>
      <td>{{x.age}}</td>
      <td>{{x.isActive}}</td>
      <td>
        <a href = "{% url 'home:deletestudent' x.id %}" class = "btn btn-danger">Delete</a>
        <a href = "{% url 'home:studentupdate' x.id %}" class = "btn btn-warning">Update</a>
      </td>
    </tr>
    {% endfor %}  
  </tbody>
</table>
  
</body>
</html>

ecommerce/templates/home/studentupdate.html
<form method="post">
  <div class="form-group">{% csrf_token %} {{form.as_p}}</div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>